artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  database_table_name: fuel_consumption_1995_2025

data_validation:
  root_dir: artifacts/data_validation
  # input_data_path: artifacts/data_ingestion/raw.csv
  errors_save_path: artifacts/data_validation/errors.json  
  # dataset_drift_report_filepath: artifacts/data_validation/dataset_drift.json
  valid_data_save_path: artifacts/data_validation/valid_data/data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  input_data_path: artifacts/data_validation/valid_data/data.csv
  preprocessor_save_path: preprocessor/preprocessor.pkl
  transformed_data_dir: artifacts/data_transformation/transformed_data

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/transformed_data/transformed_train_data.csv
  test_data_path: artifacts/data_transformation/transformed_data/transformed_test_data.csv
  model_save_path: model/best_model.pkl
  hyperparameter_tuning_report_save_path: artifacts/model_trainer/tuning_report.csv