linear_regression:
  fit_intercept: [True, False]
  normalize: [True, False]

random_forest_regressor:
  n_estimators: [50, 100, 200, 500]
  criterion: ["squared_error", "absolute_error", "friedman_mse", "poisson"]
  max_depth: [None, 5, 10, 20]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ["sqrt", "log2"]
  bootstrap: [True, False]

svr:
  kernel: ["linear", "poly", "rbf", "sigmoid"]
  C: [0.1, 1, 10, 100]
  epsilon: [0.01, 0.1, 0.5, 1.0]
  gamma: ["scale", "auto"]

knn:
  n_neighbors: [3, 5, 10]
  weights: ["uniform", "distance"]
  algorithm: ["auto", "ball_tree", "kd_tree", "brute"]
  leaf_size: [20, 30, 40]
  p: [1, 2]
